# general settings
doping: [-3.e13]
temperatures: [201, 290, 401, 506, 605, 789, 994]
bandgap: 1.33
scattering_type: auto

# electronic_structure settings
interpolation_factor: 50

# material settings
acceptor_charge: 1
deformation_potential: [1.2, 8.6]
donor_charge: 1
elastic_constant: 139.7
high_frequency_dielectric: 10.32
pop_frequency: 8.16
static_dielectric: 12.18

# performance settings
mobility_rates_only: true
write_mesh: true
